### ISSUE TITLE
ss.cpp:4:15: error: ‘sketch::EByteSetS’ has not been declared

### ISSUE THREAD

**Issue by liuwangwang1** [dnbaker/sketch#58]
when I was downloading the package according to the command in the document, the above error occurred. I tried to update `pybind11` to the latest version, but there is still a problem, maybe there are some dependencies?

**Comment by liuwangwang1** [comment]
Hi Daniel,
Thank you very much for your reply and your adjustment
When I used your branch (`bugfix`) and tried to setup again, there was no previous problem again, but I got a new ERROR with the log as follows:
`util.cpp: In lambda function:
util.cpp:105:39: error: variable ‘schism::Schismatic<int> div’ has initializer but incomplete type
  105 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:122:5: note: in expansion of macro ‘PERF_FM’
  122 |     PERF_FM(int32_t, "fastdiv", div);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:114:39: error: variable ‘schism::Schismatic<int> div’ has initializer but incomplete type
  114 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:122:5: note: in expansion of macro ‘PERF_FM’
  122 |     PERF_FM(int32_t, "fastdiv", div);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:105:39: error: variable ‘schism::Schismatic<int> div’ has initializer but incomplete type
  105 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:123:5: note: in expansion of macro ‘PERF_FM’
  123 |     PERF_FM(int32_t, "fastmod", mod);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:114:39: error: variable ‘schism::Schismatic<int> div’ has initializer but incomplete type
  114 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:123:5: note: in expansion of macro ‘PERF_FM’
  123 |     PERF_FM(int32_t, "fastmod", mod);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:105:39: error: variable ‘schism::Schismatic<long int> div’ has initializer but incomplete type
  105 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:124:5: note: in expansion of macro ‘PERF_FM’
  124 |     PERF_FM(int64_t, "fastdiv", div);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:114:39: error: variable ‘schism::Schismatic<long int> div’ has initializer but incomplete type
  114 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:124:5: note: in expansion of macro ‘PERF_FM’
  124 |     PERF_FM(int64_t, "fastdiv", div);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:105:39: error: variable ‘schism::Schismatic<long int> div’ has initializer but incomplete type
  105 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:125:5: note: in expansion of macro ‘PERF_FM’
  125 |     PERF_FM(int64_t, "fastmod", mod);
      |     ^~~~~~~
util.cpp: In lambda function:
util.cpp:114:39: error: variable ‘schism::Schismatic<long int> div’ has initializer but incomplete type
  114 |         schism::Schismatic<TYPE> div(v);\
      |                                       ^
util.cpp:125:5: note: in expansion of macro ‘PERF_FM’
  125 |     PERF_FM(int64_t, "fastmod", mod);
      |     ^~~~~~~
In file included from /usr/include/c++/9/string:52,
                 from /usr/include/c++/9/stdexcept:39,
                 from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/bits/unique_ptr.h:37,
                 from /usr/include/c++/9/memory:80,
                 from /home/liuwangwang/work_space/study_env/sketch/python/.eggs/pybind11-2.10.0-py3.8.egg/pybind11/include/pybind11/detail/../detail/common.h:248,
                 from /home/liuwangwang/work_space/study_env/sketch/python/.eggs/pybind11-2.10.0-py3.8.egg/pybind11/include/pybind11/detail/../attr.h:13,
                 from /home/liuwangwang/work_space/study_env/sketch/python/.eggs/pybind11-2.10.0-py3.8.egg/pybind11/include/pybind11/detail/class.h:12,
                 from /home/liuwangwang/work_space/study_env/sketch/python/.eggs/pybind11-2.10.0-py3.8.egg/pybind11/include/pybind11/pybind11.h:13,
                 from pysketch.h:3,
                 from util.cpp:1:
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = const int*; _OIter = int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<int>, Py_ssize_t)>::<lambda(auto:84)>]’:
util.cpp:122:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
 4343 |  *__result = __unary_op(*__first);
      |              ~~~~~~~~~~^~~~~~~~~~
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = int*; _OIter = int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<int>, Py_ssize_t)>::<lambda(auto:85)>]’:
util.cpp:122:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = const int*; _OIter = int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<int>, Py_ssize_t)>::<lambda(auto:86)>]’:
util.cpp:123:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = int*; _OIter = int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<int>, Py_ssize_t)>::<lambda(auto:87)>]’:
util.cpp:123:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = const long int*; _OIter = long int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<long int>, Py_ssize_t)>::<lambda(auto:88)>]’:
util.cpp:124:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = long int*; _OIter = long int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<long int>, Py_ssize_t)>::<lambda(auto:89)>]’:
util.cpp:124:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = const long int*; _OIter = long int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<long int>, Py_ssize_t)>::<lambda(auto:90)>]’:
util.cpp:125:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
/usr/include/c++/9/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = long int*; _OIter = long int*; _UnaryOperation = pybind11_init_sketch_util(pybind11::module_&)::<lambda(pybind11::array_t<long int>, Py_ssize_t)>::<lambda(auto:91)>]’:
util.cpp:125:5:   required from here
/usr/include/c++/9/bits/stl_algo.h:4343:24: error: void value not ignored as it ought to be
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by dnbaker** [comment]
Hi - 

I think I've patched it up now. Thanks - the error message was helpful in tracking down the problem.

It should be fixed - I'll merge it soon, but you can give it a shot now. Sorry for the trouble,

Daniel

**Comment by liuwangwang1** [comment]
Hi Daniel: 
Thank you for your adjustment. I'm sure your change is effective.
Ww
