### ISSUE TITLE
won't compile under gcc  > 11 or clang 16

### ISSUE THREAD

**Issue by joelb123** [dnbaker/sketch#65]
compiles under gcc 11, but fails under gcc 12 & 13 with the following (similar under clang-16):

x86_64-pc-linux-gnu-g++ -std=c++17 -O3 -funroll-loops -pipe -march=native -Iinclude/sketch -I. -Iinclude/blaze -Ivec -Ipybind11/include -Iinclude -fpic -Wall -Wall -Wextra -Wno-char-subscripts -Wpointer-arith -Wwrite-strings -Wdisabled-optimization -Wformat -Wcast-align -Wno-unused-function -Wno-unused-parameter -pedantic -Wunused-variable -Wno-cast-align -fno-strict-aliasing -Wreorder   -Wno-unused-parameter -pthread kthread.o testsrc/lpcqf_approx.cpp -o lpcqf_approx -lz # -fsanitize=undefined -fsanitize=address
In file included from testsrc/lpcqf_approx.cpp:1:
include/sketch/lpcqf.h: In instantiation of ‘constexpr const std::array<long double, 64> sketch::POWERS<25, 26, 64>’:
include/sketch/lpcqf.h:160:56:   required from ‘static long double sketch::LPCQF<BaseT, sigbits, flags, argnum, argdenom, ModT, NCACHED_POWERS>::ainc_estimate_count(long long int) [with BaseT = short unsigned int; long unsigned int sigbits = 2; int flags = 11; long unsigned int argnum = 52; long unsigned int argdenom = 50; ModT = unsigned int; long long int NCACHED_POWERS = 64]’
include/sketch/lpcqf.h:360:47:   required from ‘std::conditional_t<sketch::LPCQF<BaseT, sigbits, flags, argnum, argdenom, ModT, NCACHED_POWERS>::approx_inc, long double, BaseT> sketch::LPCQF<BaseT, sigbits, flags, argnum, argdenom, ModT, NCACHED_POWERS>::count_estimate(uint64_t) const [with BaseT = short unsigned int; long unsigned int sigbits = 2; int flags = 11; long unsigned int argnum = 52; long unsigned int argdenom = 50; ModT = unsigned int; long long int NCACHED_POWERS = 64; std::conditional_t<approx_inc, long double, BaseT> = long double; uint64_t = long unsigned int]’
testsrc/lpcqf_approx.cpp:16:121:   required from here
include/sketch/lpcqf.h:113:73: error: invalid use of incomplete type ‘struct std::array<long double, 64>’
  113 | constexpr std::array<long double, N> POWERS = get_ipowers<num, denom, N>();
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:36,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/memory:75,
                 from include/sketch/lpcqf.h:11:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/tuple:1595:45: note: declaration of ‘struct std::array<long double, 64>’
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
include/sketch/lpcqf.h:113:38: error: ‘constexpr const std::array<long double, 64> sketch::POWERS<25, 26, 64>’ has incomplete type
  113 | constexpr std::array<long double, N> POWERS = get_ipowers<num, denom, N>();
      |                                      ^~~~~~

**Comment by dnbaker** [comment]
Hi Joel,

Thanks for the issue! I could reproduce it, and I've patched it in [this PR](https://github.com/dnbaker/sketch/pull/66). Could you give it another shot?

Thanks,

Daniel

P.S. I saw your other issues on related projects. I'll get to them as well. Thanks for your patience!

**Comment by joelb123** [comment]
Tested and works for me under gcc 12 and 13. Throws lots of warnings about deprecated declarations, though.

**Comment by dnbaker** [comment]
Thanks again!

And I've just patched up what should be most of those remaining warnings as
well.

Thanks,

Daniel
